var t=function(c){var e=0;return function(){return e<c.length?{done:!1,value:c[e++]}:{done:!0}}},u=function(c){var e="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];return e?e.call(c):{next:t(c)}},v="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,w="function"==typeof Object.defineProperties?Object.defineProperty:function(c,e,h){c!=Array.prototype&&c!=Object.prototype&&(c[e]=h.value)},x=function(c,e){if(e){var h=v;c=c.split(".");for(var k=
0;k<c.length-1;k++){var d=c[k];d in h||(h[d]={});h=h[d]}c=c[c.length-1];k=h[c];e=e(k);e!=k&&null!=e&&w(h,c,{configurable:!0,writable:!0,value:e})}};
x("Promise",function(c){function e(){this.a=null}function h(a){return a instanceof d?a:new d(function(b){b(a)})}if(c)return c;e.prototype.b=function(a){if(null==this.a){this.a=[];var b=this;this.c(function(){b.g()})}this.a.push(a)};var k=v.setTimeout;e.prototype.c=function(a){k(a,0)};e.prototype.g=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;++b){var f=a[b];a[b]=null;try{f()}catch(g){this.f(g)}}}this.a=null};e.prototype.f=function(a){this.c(function(){throw a;
})};var d=function(a){this.b=0;this.g=void 0;this.a=[];var b=this.c();try{a(b.resolve,b.reject)}catch(f){b.reject(f)}};d.prototype.c=function(){function a(g){return function(l){f||(f=!0,g.call(b,l))}}var b=this,f=!1;return{resolve:a(this.o),reject:a(this.f)}};d.prototype.o=function(a){if(a===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof d)this.s(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.m(a):
this.i(a)}};d.prototype.m=function(a){var b=void 0;try{b=a.then}catch(f){this.f(f);return}"function"==typeof b?this.u(b,a):this.i(a)};d.prototype.f=function(a){this.j(2,a)};d.prototype.i=function(a){this.j(1,a)};d.prototype.j=function(a,b){if(0!=this.b)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.b);this.b=a;this.g=b;this.l()};d.prototype.l=function(){if(null!=this.a){for(var a=0;a<this.a.length;++a)y.b(this.a[a]);this.a=null}};var y=new e;d.prototype.s=function(a){var b=
this.c();a.h(b.resolve,b.reject)};d.prototype.u=function(a,b){var f=this.c();try{a.call(b,f.resolve,f.reject)}catch(g){f.reject(g)}};d.prototype.then=function(a,b){function f(m,n){return"function"==typeof m?function(p){try{g(m(p))}catch(q){l(q)}}:n}var g,l,r=new d(function(m,n){g=m;l=n});this.h(f(a,g),f(b,l));return r};d.prototype.catch=function(a){return this.then(void 0,a)};d.prototype.h=function(a,b){function f(){switch(g.b){case 1:a(g.g);break;case 2:b(g.g);break;default:throw Error("Unexpected state: "+
g.b);}}var g=this;null==this.a?y.b(f):this.a.push(f)};d.resolve=h;d.reject=function(a){return new d(function(b,f){f(a)})};d.race=function(a){return new d(function(b,f){for(var g=u(a),l=g.next();!l.done;l=g.next())h(l.value).h(b,f)})};d.all=function(a){var b=u(a),f=b.next();return f.done?h([]):new d(function(g,l){function r(p){return function(q){m[p]=q;n--;0==n&&g(m)}}var m=[],n=0;do m.push(void 0),n++,h(f.value).h(r(m.length-1),l),f=b.next();while(!f.done)})};return d});
var z=this||self,A=/^[\w+/_-]+[=]{0,2}$/,B=null,C=function(){var c=z.document;return(c=c.querySelector&&c.querySelector("script[nonce]"))&&(c=c.nonce||c.getAttribute("nonce"))&&A.test(c)?c:""};function D(){window.performance.mark("gapi_load_end");window.performance.measure("gapi_load","gapi_load_start","gapi_load_end");E()}var E,F=null;
function G(){if(F)return F;window.performance.mark("gapi_load_start");var c=window.colabExperiments&&window.colabExperiments.first_party_auth;return F=new Promise(function(e,h){E=e;window.gapi_onload=function(){c?E():gapi.load("auth:client",D)};var k=document.createElement("script");k.src="https://apis.google.com/js/client.js";k.async=!0;null===B&&(B=C());(e=B)&&k.setAttribute("nonce",e);k.onerror=function(){h(Error("Error loading "+k.src))};e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(k,
e)})}window.colab_gapi_loader={};window.colab_gapi_loader.load=G;G().then(function(){},function(){});
